import { createContext, useContext } from 'react'
import type { Session } from '@supabase/supabase-js'
import type { Role, SelfSignupRole } from './roles'

/**
 * The signed-in user's row from the `profiles` table.
 *
 * Note what is NOT here: no password, no token. Those live in Supabase's own
 * session handling. This is only our application's view of who someone is.
 */
export type Profile = {
  id: string
  school_id: string | null
  role: Role
  first_name: string
  last_name: string
  /** Generated by Postgres — see db/001_foundation.sql. */
  full_name: string
  email: string | null
  /** FR18. Set by a Platform Admin, never by the user. */
  is_verified: boolean
}

export type SignUpDetails = {
  firstName: string
  lastName: string
  /** Only the three self-selectable roles are accepted here. The database
   *  rejects anything else regardless of what the browser sends. */
  role: SelfSignupRole
}

export type AuthValue = {
  /** Supabase's session: null when signed out. */
  session: Session | null
  /** Our profile row. Null while loading, or if the row is somehow missing. */
  profile: Profile | null
  /** True until we know whether someone is signed in. Guard on this before
   *  redirecting, or a refresh will bounce a signed-in user to the login page. */
  loading: boolean
  /**
   * This account has an authenticator and THIS session has not satisfied it.
   *
   * Null while unknown. Guard on that before redirecting, for the same reason
   * as `loading`: treating "not yet known" as "not required" would let someone
   * through for the split second before the answer arrives.
   */
  mfaRequired: boolean | null
  /**
   * Whether this account has an authenticator at all. Distinct from
   * `mfaRequired`, which asks whether THIS SESSION still owes a code — that is
   * false both for someone who has already entered one and for someone who has
   * never set one up, and those need opposite treatment.
   *
   * Four states, not three, because 'unknown' is real and has to be actionable:
   *
   *   'loading'  — the answer is coming, wait
   *   'enrolled' — has an authenticator
   *   'none'     — definitely does not, and must set one up
   *   'unknown'  — could not be determined, which offline is the normal case:
   *                Supabase answers this over the network. Treated as "do not
   *                block", because someone already signed in got past both
   *                factors while they had a connection, and RLS is what
   *                actually guards the data either way.
   */
  mfaEnrolment: 'loading' | 'enrolled' | 'none' | 'unknown'
  signIn: (email: string, password: string) => Promise<void>
  /**
   * Returns whether Supabase withheld a session pending email confirmation.
   * The caller has to know: if it did, nothing else will happen on its own and
   * the person needs to be sent to their inbox.
   */
  signUp: (
    email: string,
    password: string,
    details: SignUpDetails,
  ) => Promise<{ needsEmailConfirmation: boolean }>
  signOut: () => Promise<void>
  /** Email a one-time link that lets someone choose a new password. */
  requestPasswordReset: (email: string) => Promise<void>
  /**
   * Set a new password with no proof beyond holding the session.
   *
   * For the reset flow ONLY, where the person has just proved they can read
   * the account's mailbox and by definition cannot supply the old password.
   * Anywhere else, use `changePassword`.
   */
  setNewPassword: (password: string) => Promise<void>
  /**
   * Change the password, proving the old one first.
   *
   * What this protects against is an unattended signed-in laptop: without the
   * check, anyone who walks up to one can take the account over permanently
   * and lock its owner out. These are shared classroom machines.
   */
  changePassword: (
    currentPassword: string,
    newPassword: string,
  ) => Promise<void>
}

export const AuthContext = createContext<AuthValue | null>(null)

/** Read the current auth state. Throws if used outside <AuthProvider>. */
export function useAuth(): AuthValue {
  const value = useContext(AuthContext)
  if (!value) {
    throw new Error('useAuth must be used inside <AuthProvider>')
  }
  return value
}
